server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  # Redirige cualquier ruta al index.html para que Angular maneje el routing
  location / {
    try_files $uri $uri/ /index.html;
  }
}
